var x = {
  _readableState: {
    objectMode: false,
    highWaterMark: 16384,
    buffer: { head: null, tail: null, length: 0 },
    length: 0,
    pipes: null,
    pipesCount: 0,
    flowing: null,
    ended: false,
    endEmitted: false,
    reading: false,
    sync: true,
    needReadable: false,
    emittedReadable: false,
    readableListening: false,
    resumeScheduled: false,
    defaultEncoding: 'utf8',
    ranOut: false,
    awaitDrain: 0,
    readingMore: true,
    decoder: null,
    encoding: null
  },
  readable: true,
  domain: null,
  _events: {},
  _eventsCount: 0,
  _maxListeners: undefined,
  socket:
  {
    connecting: false,
    _hadError: false,
    _handle:
    {
      bytesRead: 563,
      _externalStream: {},
      fd: 14,
      reading: true,
      owner: [Circular],
      onread: [Function: onread],
      onconnection: null,
      writeQueueSize: 0,
      _consumed: true
    },
    _parent: null,
    _host: null,
    _readableState:
    {
      objectMode: false,
      highWaterMark: 16384,
      buffer: [Object],
      length: 0,
      pipes: null,
      pipesCount: 0,
      flowing: true,
      ended: false,
      endEmitted: false,
      reading: true,
      sync: false,
      needReadable: true,
      emittedReadable: false,
      readableListening: false,
      resumeScheduled: false,
      defaultEncoding: 'utf8',
      ranOut: false,
      awaitDrain: 0,
      readingMore: false,
      decoder: null,
      encoding: null
    },
    readable: true,
    domain: null,
    _events:
    {
      end: [Object],
      finish: [Function: onSocketFinish],
      _socketEnd: [Function: onSocketEnd],
      drain: [Object],
      timeout: [Function: bound socketOnTimeout],
      data: [Function: bound socketOnData],
      error: [Function: bound socketOnError],
      close: [Object],
      resume: [Function: onSocketResume],
      pause: [Function: onSocketPause]
    },
    _eventsCount: 10,
    _maxListeners: undefined,
    _writableState:
    {
      objectMode: false,
      highWaterMark: 16384,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      decodeStrings: false,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: false,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      bufferedRequest: null,
      lastBufferedRequest: null,
      pendingcb: 1,
      prefinished: false,
      errorEmitted: false,
      bufferedRequestCount: 0,
      corkedRequestsFree: [Object]
    },
    writable: true,
    allowHalfOpen: true,
    destroyed: false,
    _bytesDispatched: 324,
    _sockname: null,
    _pendingData: null,
    _pendingEncoding: '',
    server:
    {
      domain: null,
      _events: [Object],
      _eventsCount: 6,
      _maxListeners: undefined,
      _connections: 2,
      _handle: [Object],
      _usingSlaves: false,
      _slaves: [],
      _unref: false,
      allowHalfOpen: true,
      pauseOnConnect: false,
      httpAllowHalfOpen: false,
      timeout: 120000,
      _pendingResponseData: 0,
      maxHeadersCount: null,
      _connectionKey: '4:127.0.0.1:3001'
    },
    _server:
    {
      domain: null,
      _events: [Object],
      _eventsCount: 6,
      _maxListeners: undefined,
      _connections: 2,
      _handle: [Object],
      _usingSlaves: false,
      _slaves: [],
      _unref: false,
      allowHalfOpen: true,
      pauseOnConnect: false,
      httpAllowHalfOpen: false,
      timeout: 120000,
      _pendingResponseData: 0,
      maxHeadersCount: null,
      _connectionKey: '4:127.0.0.1:3001'
    },
    _idleTimeout: 120000,
    _idleNext:
    {
      connecting: false,
      _hadError: false,
      _handle: [Object],
      _parent: null,
      _host: null,
      _readableState: [Object],
      readable: true,
      domain: null,
      _events: [Object],
      _eventsCount: 10,
      _maxListeners: undefined,
      _writableState: [Object],
      writable: true,
      allowHalfOpen: true,
      destroyed: false,
      _bytesDispatched: 0,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: [Object],
      _server: [Object],
      _idleTimeout: 120000,
      _idleNext: [Object],
      _idlePrev: [Circular],
      _idleStart: 928530,
      parser: [Object],
      on: [Function: socketOnWrap],
      _paused: false,
      read: [Function],
      _consuming: true,
      _httpMessage: [Object]
    },
    _idlePrev:
    {
      _idleNext: [Circular],
      _idlePrev: [Object],
      _timer: [Object],
      _unrefed: true,
      msecs: 120000,
      nextTick: false
    },
    _idleStart: 944969,
    parser:
    {
      '0': [Function: parserOnHeaders],
      '1': [Function: parserOnHeadersComplete],
      '2': [Function: parserOnBody],
      '3': [Function: parserOnMessageComplete],
      '4': [Function: bound onParserExecute],
      _headers: [],
      _url: '',
      _consumed: true,
      socket: [Circular],
      incoming: [Circular],
      outgoing: null,
      maxHeaderPairs: 2000,
      onIncoming: [Function: bound parserOnIncoming]
    },
    on: [Function: socketOnWrap],
    _paused: false,
    read: [Function],
    _consuming: true,
    _httpMessage:
    {
      domain: null,
      _events: [Object],
      _eventsCount: 1,
      _maxListeners: undefined,
      output: [],
      outputEncodings: [],
      outputCallbacks: [],
      outputSize: 0,
      writable: true,
      _last: true,
      upgrading: false,
      chunkedEncoding: false,
      shouldKeepAlive: false,

      unkedEncodingByDefault: true,
      sendDate: true,
      _removedHeader: {},
      _contentLength: null,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [Circular],
      connection: [Circular],
      _header: 'HTTP/1.1 200 OK\r\nContent-Type: text/plain; charset=UTF-8\r\nContent-Length: 100\r\nAccess-Control-Allow-Origin: *\r\nSet-Cookie: io=ymVgy1nFJ2NiymRcAAAE; Path=/; HttpOnly\r\nDate: Wed, 12 Jul 2017 20:16:19 GMT\r\nConnection: close\r\n\r\n',
      _headers: null,
      _headerNames: {},
      _onPendingData: [Function: bound updateOutgoingData],
      _sent100: false,
      _expect_continue: false,
      statusMessage: 'OK',
      statusCode: 200
    },
    _peername: { address: '127.0.0.1', family: 'IPv4', port: 58402 }
  },
  connection:
  {
    connecting: false,
    _hadError: false,
    _handle:
    {
      bytesRead: 563,
      _externalStream: {},
      fd: 14,
      reading: true,
      owner: [Circular],
      onread: [Function: onread],
      onconnection: null,
      writeQueueSize: 0,
      _consumed: true
    },
    _parent: null,
    _host: null,
    _readableState:
    {
      objectMode: false,
      highWaterMark: 16384,
      buffer: [Object],
      length: 0,
      pipes: null,
      pipesCount: 0,
      flowing: true,
      ended: false,
      endEmitted: false,
      reading: true,
      sync: false,
      needReadable: true,
      emittedReadable: false,
      readableListening: false,
      resumeScheduled: false,
      defaultEncoding: 'utf8',
      ranOut: false,
      awaitDrain: 0,
      readingMore: false,
      decoder: null,
      encoding: null
    },
    readable: true,
    domain: null,
    _events:
    {
      end: [Object],
      finish: [Function: onSocketFinish],
      _socketEnd: [Function: onSocketEnd],
      drain: [Object],
      timeout: [Function: bound socketOnTimeout],
      data: [Function: 
        bound socketOnData],
      error: [Function: bound socketOnError],
      close: [Object],
      resume: [Function: onSocketResume],
      pause: [Function: onSocketPause]
    },
    _eventsCount: 10,
    _maxListeners: undefined,
    _writableState:
    {
      objectMode: false,
      highWaterMark: 16384,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      decodeStrings: false,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: false,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      bufferedRequest: null,
      lastBufferedRequest: null,
      pendingcb: 1,
      prefinished: false,
      errorEmitted: false,
      bufferedRequestCount: 0,
      corkedRequestsFree: [Object]
    },
    writable: true,
    allowHalfOpen: true,
    destroyed: false,
    _bytesDispatched: 324,
    _sockname: null,
    _pendingData: null,
    _pendingEncoding: '',
    server:
    {
      domain: null,
      _events: [Object],
      _eventsCount: 6,
      _maxListeners: undefined,
      _connections: 2,
      _handle: [Object],
      _usingSlaves: false,
      _slaves: [],
      _unref: false,
      allowHalfOpen: true,
      pauseOnConnect: false,
      httpAllowHalfOpen: false,
      timeout: 120000,
      _pendingResponseData: 0,
      maxHeadersCount: null,
      _connectionKey: '4:127.0.0.1:3001'
    },
    _server:
    {
      domain: null,
      _events: [Object],
      _eventsCount: 6,
      _maxListeners: undefined,
      _connections: 2,
      _handle: [Object],
      _usingSlaves: false,
      _slaves: [],
      _unref: false,
      allowHalfOpen: true,
      pauseOnConnect: false,
      httpAllowHalfOpen: false,
      timeout: 120000,
      _pendingResponseData: 0,
      maxHeadersCount: null,
      _connectionKey: '4:127.0.0.1:3001'
    },
    _idleTimeout: 120000,
    _idleNext:
    {
      connecting: false,
      _hadError: false,
      _handle: [Object],
      _parent: null,
      _host: null,
      _readableState: [Object],
      readable: true,
      domain: null,
      _events: [Object],
      _eventsCount: 10,
      _maxListeners: undefined,
      _writableState: [Object],
      writable: true,
      allowHalfOpen: true,
      destroyed: false,
      _bytesDispatched: 0,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: [Object],
      _server: [Object],
      _idleTimeout: 120000,
      _idleNext: [Object],
      _idlePrev: [Circular],
      _idleStart: 928530,
      parser: [Object],
      on: [Function: socketOnWrap],
      _paused: false,
      read: [Function],
      _consuming: true,
      _httpMessage: [Object]
    },
    _idlePrev:
    {
      _idleNext: [Circular],
      _idlePrev: [Object],
      _timer: [Object],
      _unrefed: true,
      msecs: 120000,
      nextTick: false
    },
    _idleStart: 944969,
    parser:
    {
      '0': [Function: parserOnHeaders],
      '1': [Function: parserOnHeadersComplete],
      '2': [Function: parserOnBody],
      '3': [Function: parserOnMessageComplete],
      '4': [Function: bound onParserExecute],
      _headers: [],
      _url: '',
      _consumed: true,
      socket: [Circular],
      incoming: [Circular],
      outgoing: null,
      maxHeaderPairs: 2000,
      onIncoming: [Function: bound parserOnIncoming]
    },
    on: [Function: socketOnWrap],
    _paused: false,
    read: [Function],
    _consuming: true,
    _httpMessage:
    {
      domain: null,
      _events: [Object],
      _eventsCount: 1,
      _maxListeners: undefined,
      output: [],
      outputEncodings: [],
      outputCallbacks: [],
      outputSize: 0,
      writable: true,
      _last: true,
      upgrading: false,
      chunkedEncoding: "",

      shouldKeepAlive: false,
      useChunkedEncodingByDefault: true,
      sendDate: true,
      _removedHeader: {},
      _contentLength: null,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [Circular],
      connection: [Circular],
      _header: 'HTTP/1.1 200 OK\r\nContent-Type: text/plain; charset=UTF-8\r\nContent-Length: 100\r\nAccess-Control-Allow-Origin: *\r\nSet-Cookie: io=ymVgy1nFJ2NiymRcAAAE; Path=/; HttpOnly\r\nDate: Wed, 12 Jul 2017 20:16:19 GMT\r\nConnection: close\r\n\r\n',
      _headers: null,
      _headerNames: {},
      _onPendingData: [Function: bound updateOutgoingData],
      _sent100: false,
      _expect_continue: false,
      statusMessage: 'OK',
      statusCode: 200
    },
    _peername: { address: '127.0.0.1', family: 'IPv4', port: 58402 }
  },
  httpVersionMajor: 1,
  httpVersionMinor: 1,
  httpVersion: '1.1',
  complete: false,
  headers:
  {
    'x-forwarded-host': 'local.thelazycoder.com:3000',
    'x-forwarded-proto': 'http',
    'x-forwarded-port': '3000',
    'x-forwarded-for': '10.0.0.101',
    cookie: 'io=8OedVNS00zVz1I7JAAAC',
    'accept-language': 'en-US,en;q=0.8',
    'accept-encoding': 'gzip, deflate',
    referer: 'http://local.thelazycoder.com:3000/',
    'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36',
    accept: '*/*',
    'cache-control': 'no-cache',
    pragma: 'no-cache',
    connection: 'close',
    host: 'localhost:3001'
  },
  rawHeaders:
  ['x-forwarded-host',
    'local.thelazycoder.com:3000',
    'x-forwarded-proto',
    'http',
    'x-forwarded-port',
    '3000',
    'x-forwarded-for',
    '10.0.0.101',
    'cookie',
    'io=8OedVNS00zVz1I7JAAAC',
    'accept-language',
    'en-US,en;q=0.8',
    'accept-encoding',
    'gzip, deflate',
    'referer',
    'http://local.thelazycoder.com:3000/',
    'user-agent',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36',
    'accept',
    '*/*',
    'cache-control',
    'no-cache',
    'pragma',
    'no-cache',
    'connection',
    'close',
    'host',
    'localhost:3001'],
  trailers: {},
  rawTrailers: [],
  upgrade: false,
  url: '/socket.io/?EIO=3&transport=polling&t=LquSVZ5',
  method: 'GET',
  statusCode: null,
  statusMessage: null,
  client:
  {
    connecting: false,
    _hadError: false,
    _handle:
    {
      bytesRead: 563,
      _externalStream: {},
      fd: 14,
      reading: true,
      owner: [Circular],
      onread: [Function: onread],
      onconnection: null,
      writeQueueSize: 0,
      _consumed: true
    },
    _parent: null,
    _host: null,
    _readableState:
    {
      objectMode: false,
      highWaterMark: 16384,
      buffer: [Object],
      length: 0,
      pipes: null,
      pipesCount: 0,
      flowing: true,
      ended: false,
      endEmitted: false,
      reading: true,
      sync: false,
      needReadable: true,
      emittedReadable: false,
      readableListening: false,
      resumeScheduled: false,
      defaultEncoding: 'utf8',
      ranOut: false,
      awaitDrain: 0,
      readingMore: false,
      decoder: null,
      encoding: null
    },
    readable: true,
    domain: null,
    _events:
    {
      end: [Object],
      finish: [Function: onSocketFinish],
      _socketEnd: [Function: onSocketEnd],
      drain: [Object],
      timeout: [Function: bound socketOnTimeout],
      data: [Function: bound socketOnData],
      error: [Function: bound socketOnError],
      close: [Object],
      resume: [Function: onSocketResume],
      pause: [Function: onSocketPause]
    },
    _eventsCount: 10,
    _maxListeners: undefined,
    _writableState:
    {
      objectMode: false,
      highWaterMark: 16384,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      decodeStrings: false,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: false,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      bufferedRequest: null,
      lastBufferedRequest: null,
      pendingcb: 1,
      prefinished: false,
      errorEmitted: false,
      bufferedRequestCount: 0,
      corkedRequestsFree: [Object]
    },
    writable: true,
    allowHalfOpen: true,
    destroyed: false,
    _bytesDispatched: 324,
    _sockname: null,
    _pendingData: null,
    _pendingEncoding: '',
    server:
    {
      domain: null,
      _events: [Object],
      _eventsCount: 6,
      _maxListeners: undefined,
      _connections: 2,
      _handle: [Object],
      _usingSlaves: false,
      _slaves: [],
      _unref: false,
      allowHalfOpen: true,
      pauseOnConnect: false,
      httpAllowHalfOpen: false,
      timeout: 120000,
      _pendingResponseData: 0,
      maxHeadersCount: null,
      _connectionKey: '4:127.0.0.1:3001'
    },
    _server:
    {
      domain: null,
      _events: [Object],
      _eventsCount: 6,
      _maxListeners: undefined,
      _connections: 2,
      _handle: [Object],
      _usingSlaves: false,
      _slaves: [],
      _unref: false,
      allowHalfOpen: true,
      pauseOnConnect: false,
      httpAllowHalfOpen: false,
      timeout: 120000,
      _pendingResponseData: 0,
      maxHeadersCount: null,
      _connectionKey: '4:127.0.0.1:3001'
    },
    _idleTimeout: 120000,
    _idleNext:
    {
      connecting: false,
      _hadError: false,
      _handle: [Object],
      _parent: null,
      _host: null,
      _readableState: [Object],
      readable: true,
      domain: null,
      _events: [Object],
      _eventsCount: 10,
      _maxListeners: undefined,
      _writableState: [Object],
      writable: true,
      allowHalfOpen: true,


      _bytesDispatched: 0,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: [Object],
      _server: [Object],
      _idleTimeout: 120000,
      _idleNext: [Object],
      _idlePrev: [Circular],
      _idleStart: 928530,
      parser: [Object],
      on: [Function: socketOnWrap],
      _paused: false,
      read: [Function],
      _consuming: true,
      _httpMessage: [Object]
    },
    _idlePrev:
    {
      _idleNext: [Circular],
      _idlePrev: [Object],
      _timer: [Object],
      _unrefed: true,
      msecs: 120000,
      nextTick: false
    },
    _idleStart: 944969,
    parser:
    {
      '0': [Function: parserOnHeaders],
      '1': [Function: parserOnHeadersComplete],
      '2': [Function: parserOnBody],
      '3': [Function: parserOnMessageComplete],
      '4': [Function: bound onParserExecute],
      _headers: [],
      _url: '',
      _consumed: true,
      socket: [Circular],
      incoming: [Circular],
      outgoing: null,
      maxHeaderPairs: 2000,
      onIncoming: [Function: bound parserOnIncoming]
    },
    on: [Function: socketOnWrap],
    _paused: false,
    read: [Function],
    _consuming: true,
    _httpMessage:
    {
      domain: null,
      _events: [Object],
      _eventsCount: 1,
      _maxListeners: undefined,
      output: [],
      outputEncodings: [],
      outputCallbacks: [],
      outputSize: 0,
      writable: true,
      _last: true,
      upgrading: false,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      useChunkedEncodingByDefault: true,
      sendDate: true,
      _removedHeader: {},
      _contentLength: null,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [Circular],
      connection: [Circular],
      _header: 'HTTP/1.1 200 OK\r\nContent-Type: text/plain; charset=UTF-8\r\nContent-Length: 100\r\nAccess-Control-Allow-Origin: *\r\nSet-Cookie: io=ymVgy1nFJ2NiymRcAAAE; Path=/; HttpOnly\r\nDate: Wed, 12 Jul 2017 20:16:19 GMT\r\nConnection: close\r\n\r\n',
      _headers: null,
      _headerNames: {},
      _onPendingData: [Function: bound updateOutgoingData],
      _sent100: false,
      _expect_continue: false,
      statusMessage: 'OK',
      statusCode: 200
    },
    _peername: { address: '127.0.0.1', family: 'IPv4', port: 58402 }
  },
  _consuming: false,
  _dumped: false,
  _query: { EIO: '3', transport: 'polling', t: 'LquSVZ5' },
  res:
  {
    domain: null,
    _events: { finish: [Function: bound resOnFinish] },
    _eventsCount: 1,
    _maxListeners: undefined,
    output: [],
    outputEncodings: [],
    outputCallbacks: [],
    outputSize: 0,
    writable: true,
    _last: true,
    upgrading: false,
    chunkedEncoding: false,
    shouldKeepAlive: false,
    useChunkedEncodingByDefault: true,
    sendDate: true,
    _removedHeader: {},
    _contentLength: null,
    _hasBody: true,
    _trailer: '',
    finished: true,
    _headerSent: true,
    socket:
    {
      connecting: false,
      _hadError: false,
      _handle: [Object],
      _parent: null,
      _host: null,
      _readableState: [Object],
      readable: true,
      domain: null,
      _events: [Object],
      _eventsCount: 10,
      _maxListeners: undefined,
      _writableState: [Object],
      writable: true,
      allowHalfOpen: true,
      destroyed: false,
      _bytesDispatched: 324,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: [Object],
      _server: [Object],
      _idleTimeout: 120000,
      _idleNext: [Object],
      _idlePrev: [Object],
      _idleStart: 944969,
      parser: [Object],
      on: [Function: socketOnWrap],
      _paused: false,
      read: [Function],
      _consuming: true,
      _httpMessage: [Circular],
      _peername: [Object]
    },
    connection:
    {
      connecting: false,
      _hadError: false,
      _handle: [Object],
      _parent: null,
      _host: null,
      _readableState: [Object],
      readable: true,
      domain: null,
      _events: [Object],
      _eventsCount: 10,
      _maxListeners: undefined,
      _writableState: [Object],
      writable: true,
      allowHalfOpen: true,
      destroyed: false,
      _bytesDispatched: 324,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: [Object],
      _server: [Object],
      _idleTimeout: 120000,
      _idleNext: [Object],
      _idlePrev: [Object],
      _idleStart: 944969,
      parser: [Object],
      on: [Function: socketOnWrap],
      _paused: false,
      read: [Function],
      _consuming: true,
      _httpMessage: [Circular],
      _peername: [Object]
    },
    _header: 'HTTP/1.1 200 OK\r\nContent-Type: text/plain; charset=UTF-8\r\nContent-Length: 100\r\nAccess-Control-Allow-Origin: *\r\nSet-Cookie: io=ymVgy1nFJ2NiymRcAAAE; Path=/; HttpOnly\r\nDate: Wed, 12 Jul 2017 20:16:19 GMT\r\nConnection: close\r\n\r\n',
    _headers: null,
    _headerNames: {},
    _onPendingData: [Function: bound updateOutgoingData],
    _sent100: false,
    _expect_continue: false,
    statusMessage: 'OK',
    statusCode: 200
  },
  cleanup: [Function: cleanup]
}